trigger: 
- main

pr:
  branches:
    include:
    - main
  paths:
    include:
    - test.yml

pool:
  vmImage: windows-latest

jobs:
- job: first_commit
  displayName: check_first_commit
  steps:
  - script: echo $(Build.SourceVersion)
  - script: echo pr1-build1


- job: second_commit
  displayName: check_second_commit
  steps:
  - script: echo $(Build.SourceVersion)



